services:
  api:
    build: .
    ports: [ "8000:8000" ]
    env_file: [ .env ]
    depends_on: [ db, cache ]
    security_opt: [ "no-new-privileges:true" ]
    read_only: true
    cap_drop: [ "ALL" ]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyberhack
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  cache:
    image: redis:7-alpine
volumes:
  pgdata:
