name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Unit tests (no integrations)
        working-directory: backend
        env: { DRY_RUN: "1" }
        run: |
          pytest -q -m "not integration" || pytest -q
      - name: Build & start minimal stack
        env: { DRY_RUN: "1" }
        run: |
          docker compose --profile ci up -d --build backend tools-runner
      - name: Wait for health
        run: |
          for i in {1..30}; do
            curl -fsS http://localhost:8000/health && exit 0
            sleep 2
          done
          echo "health check failed"; exit 1
      - name: Tear down
        if: always()
        run: docker compose down -v
