name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint & Test
        run: |
          cd frontend && npm install && npm run lint
          cd ../backend && pip install -r requirements.txt && black --check .
